version: '3.9'

services:
  strapi:
    build: .
    #container_name: strapi
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${PG_HOST}
      DATABASE_PORT: ${PG_PORT}
      DATABASE_NAME: ${PG_DB}
      DATABASE_USERNAME: ${PG_USER}
      DATABASE_PASSWORD: ${PG_PASSWORD}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
